FROM ubuntu:24.04

ARG DOCKER_USER=dev

COPY docker/bashrc /etc/bash.bashrc
RUN chmod a+rwx /etc/bash.bashrc

RUN apt-get update && apt-get install --yes --no-install-recommends \
  lsb-release wget software-properties-common gnupg \
  build-essential gcc-13 g++-13 cpp-13 make ninja-build ccache cmake python3 python3-pip lcov sudo git gdb curl \
  openssl libssl-dev
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100 \
  && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 \
  && update-alternatives --install /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-13 100 \
  && update-alternatives --install /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-13 100 \
  && update-alternatives --install /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-13 100 \
  && update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-13 100
RUN apt-get install --yes --no-install-recommends python3-venv \
  && python3 -m venv /opt/conan \
  && /opt/conan/bin/pip install --no-cache-dir conan==1.63.0
ENV PATH="/opt/conan/bin:${PATH}"
# Limit memory use when compiling documentation tools in Docker Desktop.
ARG DOXYGEN_JOBS=2
RUN apt-get install --yes flex bison \
  && mkdir -p doxygen/build && cd doxygen \
  && wget -qO- https://github.com/doxygen/doxygen/releases/download/Release_1_10_0/doxygen-1.10.0.src.tar.gz | tar xvz --strip-components=1 \
  && cd build && cmake -G "Unix Makefiles" .. && make -j"${DOXYGEN_JOBS}" && make install \
  && apt-get purge -y bison flex && apt-get autoclean --yes \
  && cd ../.. && rm -rf doxygen

RUN useradd --create-home --shell /bin/bash --groups sudo $DOCKER_USER

USER $DOCKER_USER
