name: ci

on:
  push:
    branches:
      - "**"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Debug GCC 13 C++20
        run: ./build.sh docker=gcc13 debug clean uban=on asan=on test
      - name: Build Release GCC 13 C++20
        run: ./build.sh docker=gcc13 release clean test doc

      - name: Build Debug Clang 17 C++20
        run: ./build.sh docker=clang17 debug clean uban=on asan=on test
      - name: Build Release Clang 17 C++20
        run: ./build.sh docker=clang17 release clean test doc

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: build/release/doc/html

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Conan 1.x
        run: |
          echo 'export PATH="/opt/homebrew/opt/conan@1/bin:$PATH"' >> /Users/runner/.bash_profile
          brew install conan@1
          conan profile new default --detect

      - name: Build Debug AppleClang C++20
        run: ./build.sh debug clean uban=on asan=on test
      - name: Build Release AppleClang C++20
        run: ./build.sh release clean test
